- name: Fieldset form example
  id  : fieldset
  type: fieldset
  help: >
    This form demonstrates a typical fieldset form. The form has string, number and text fields, all required.
  fields:
  - name: A string field
    id  : string
    type: string
    description: A string field
    validation : required
    visibility : web
    readonly   : false
  - name: A number field
    id  : number
    type: number
    description: A number field
    validation : required,custom[integer]
    visibility : web
    readonly   : false
  - name: A double field
    id  : double
    type: double
    description: A double field
    validation : required,custom[double]
    visibility : web
    readonly   : false
  - name: A text field
    id  : text
    type: text
    description: A text field
    validation : required
    visibility : web
    readonly   : false
  - name: A readonly field
    id  : readOnly
    type: text
    description: A text field
    validation : none
    visibility : web
    readonly   : true
  - name: A tango-only field
    id  : tangoOnly
    type: text
    description: A text field
    validation : none
    visibility : tango
    readonly   : false
- name: An upload form example
  id  : upload-1
  type: upload
  help: >
    This form demonstrates upload field type. Upload type forms may contain only one field, not required.
    All files will be uploaded asynchronously via iFrame transport.
  fields:
  - name: some file to upload
    id  : uploadFile
    description: Please browse for a file
    type       : file
    validation : none
    visibility : web
    readonly   : false
- name: Choice-form example
  id  : choice
  type: multichoice
  help: >
    This form demonstrates multichoice. Each choice has it owns number of fields. All fields will be stored on the server.
    Each choice is stored as a boolean value, true means chosen. Fields should not be required.
  fields:
  - name: choice-1
    id  : choice-1
    description: Choice 1
    type       : choice
    validation : none
    visibility : web
    readonly   : false
    fields:
    - name: field-1
      id  : field-1
      description: Field 1
      type       : string
      validation : none
      visibility : web
      readonly   : false
    - name: field-2
      id  : field-2
      description: Field 2
      type       : number
      validation : custom[integer]
      visibility : web
      readonly   : false
    - name: field-3
      id  : field-3
      description: Field 3
      type: text
      validation : none
      visibility : web
      readonly   : false
  - name: choice-2
    id  : choice-2
    description: Choice 2
    type: choice
    validation : none
    visibility : web
    readonly   : false
    fields:
    - name: field-4
      id  : field-4
      description: Field 4
      type: number
      validation: custom[integer]
      visibility: web
      readonly  : false
    - name: field-5
      id  : field-5
      description: Field 5
      type: number
      validation: custom[integer]
      visibility: web
      readonly  : false
  - name: choice-3
    id  : choice-3
    description: Choice 3
    type: choice
    validation: none
    visibility: web
    readonly  : false,
    fields:
    - name: field-6
      id  : field-6
      description: Field 6
      type: string
      validation: none
      visibility: web
      readonly  : false
    - name: field-7
      id  : field-7
      description: Field 7
      type: number
      validation: custom[integer]
      visibility: web
      readonly  : false
    - name: field-8
      id  : field-8
      description: Field 8
      type: text
      validation: none
      visibility: web
      readonly  : false